config/routes.rb
Rails.application.routes.draw do

  resources :teachers
  resources :users
  resources :attendances
  resources :events
  resources :students

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
		get 'logout' => :destroy
	end

   root 'events#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :event
	belongs_to :student
	validates :event_id, presence: true
	validates :student_id, presence: true
	validates :student_id, uniqueness: { scope: :event_id }
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
		if is_student
		 	event = Event.find(params[:event_id])
			@student = get_student
			@attendance = @student.attendances.build(event: event)

		  respond_to do |format|
		    if @attendance.save
		      format.html {redirect_to events_path }
					format.js
		      format.json { render :show, status: :created, location: @attendance }
		    else
		      format.html { render :new }
		      format.json { render json: @attendance.errors, status: :unprocessable_entity }
		    end
		  end
		else
			respond_to do |format|
		      format.html {redirect_to events_path }
		  end
		
		end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
		if is_root or (is_student and get_student.id_number === @attendance.student.id_number) or (is_teacher and get_teacher.id_number === @attendance.event.id_number)
		  @attendance.destroy
		  respond_to do |format|
		    format.html {redirect_to events_path }
		    format.json { head :no_content }
				format.js
		  end
		else 
			redirect_to events_path, notice: "you can't kick someone else out" 
		end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:student_id, :event_id)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_attendance.html.erb
	<tr><td><%= attendance.student.name %></td><td><%= button_to 'Kick out',attendance_path(id: attendance.id), :method => :delete %></td></tr>

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/_student.html.erb
working

<ul>
	<li><%= student.name %></li>
	<% student.attendances.each do |a| %>
		<% e = Event.find(a.event_id) %>
	<li><%= e.module %> </li>
	<% end %>
</ul>

app/views/attendances/create.js.erb
$('#student').html("<%= escape_javascript render(@student) %>")

app/views/attendances/destroy.js.erb
$('#student').html("<%= escape_javascript render(@student) %>")

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.student_id %></td>
        <td><%= attendance.event_id %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @attendance.student_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @attendance.event_id %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>