config/routes.rb
Rails.application.routes.draw do

  resources :teachers
  resources :users
  resources :attendances
  resources :events
  resources :students

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
		get 'logout' => :destroy
	end

   root 'events#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AS2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>
<table id "main_table" cellspacing="0" cellpadding="0">
<tr id = "r1">
<td class = "c1"><%= @page_title || "Attendance Sheet" %></td>
<td class = "c2"><div id="top_bar">
								<ul>
										<li><%= link_to "Home", events_path %></li>
										<li><%= link_to "New Event", new_event_path %></li>
										<li><%= link_to "New Student", new_student_path %></li>
										<li><%= link_to "New User", new_user_path %></li>
										<li><%= link_to "New Teacher", new_teacher_path %></li>
								</ul>	</td>
								</div>
<td class = "c3"><%= button_to "Me", events_path, remote: true, :method => :get %></td>
</tr>
<tr id = "r2">
<td class = "c1">
	<div id="left_side_panel">
	<%if is_root %>
	<ul>
		<li>Root</li>
		<li><%= link_to "students", students_path %></li>
		<li><%= link_to "attendances", attendances_path %></li>
		<li><%= link_to "teachers", teachers_path %></li>
	</ul>
	<% end %>
	</div>

</td>
<td class = "c2"><%= yield %></td>
<td class = "c3"><div id="right_side_panel">
											<% if session[:id_number] %>
												<% if is_student %>
													<%= get_student.name %>
												<% elsif is_teacher %> 
													<%= get_teacher.name %>
												<% end %>
											<% end %>
											<% if is_student %>
												
												<div id="student"><ul><li style="color:red;">Attending</li></ul><%= render get_student %></div>
												<ul><% id = get_student.id %>
												<li><%= link_to "going to", student_path(id) %> </li></ul>
											<% end %>
											<% if is_teacher %>
												<div id="teacher"><ul><li style="color:red;">Teaching</li></ul><%= render get_teacher %></div>
												<% id = get_teacher.id %>							
												<ul><li><%= link_to "teaching", teacher_path(id) %> </li></ul>
											<% end %>
											<% if session[:id_number] === nil  %>
												<ul><li><%= link_to "login", login_path %> </li></ul>
											<% else %>
												<ul>
												<li><%= link_to "logout", logout_path %> </li>
												</ul>
											<% end %>
								</div></td>
</tr>
<tr id = "r3">
<td class = "c1"></td>
<td class = "c2"></td>
<td class = "c3"></td>
</tr>
</body>



</html>